jobs:
  - job: build_docker_image
    displayName: Build and publish Docker image
    pool:
      vmImage:  'ubuntu-latest'
    variables:
      ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
        tag:  latest
      ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
        tempBranchName: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
        branchNameNoSlash: $[ replace(variables['tempBranchName'], '/', '-') ]
        branchName: $[ replace(variables['branchNameNoSlash'], '_', '-') ]
        tag: $(branchName)
    
    steps:
    - checkout: self
    - template: azure-templates/step-template-download-osp-libs-linux.yml
    
    - task: Docker@2
      name: DockerBuild
      displayName: Build image
      inputs:
        command: build
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: $(tag)

    - task: Docker@2
      name: DockerPush
      displayName: Push image to container registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: $(tag)