# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_points.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10set_points.proto\x12\nset_points\"k\n\x10SetPointsRequest\x12\t\n\x01t\x18\x01 \x01(\x01\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01u\x18\x04 \x01(\x01\x12\t\n\x01v\x18\x05 \x01(\x01\x12\x0f\n\x07heading\x18\x06 \x01(\x01\x12\x0f\n\x07loading\x18\x07 \x01(\x01\"\xad\x01\n\x11SetPointsResponse\x12\x17\n\x0fspeed_set_point\x18\x01 \x01(\x01\x12\x19\n\x11heading_set_point\x18\x02 \x01(\x01\x12\x14\n\x0cspeed_pid_on\x18\x03 \x01(\x08\x12\x16\n\x0eheading_pid_on\x18\x04 \x01(\x08\x12\x19\n\x11speed_gain_adjust\x18\x05 \x01(\x01\x12\x1b\n\x13heading_gain_adjust\x18\x06 \x01(\x01\x32Z\n\tSetPoints\x12M\n\x0cGetSetPoints\x12\x1c.set_points.SetPointsRequest\x1a\x1d.set_points.SetPointsResponse\"\x00\x62\x06proto3')



_SETPOINTSREQUEST = DESCRIPTOR.message_types_by_name['SetPointsRequest']
_SETPOINTSRESPONSE = DESCRIPTOR.message_types_by_name['SetPointsResponse']
SetPointsRequest = _reflection.GeneratedProtocolMessageType('SetPointsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETPOINTSREQUEST,
  '__module__' : 'set_points_pb2'
  # @@protoc_insertion_point(class_scope:set_points.SetPointsRequest)
  })
_sym_db.RegisterMessage(SetPointsRequest)

SetPointsResponse = _reflection.GeneratedProtocolMessageType('SetPointsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETPOINTSRESPONSE,
  '__module__' : 'set_points_pb2'
  # @@protoc_insertion_point(class_scope:set_points.SetPointsResponse)
  })
_sym_db.RegisterMessage(SetPointsResponse)

_SETPOINTS = DESCRIPTOR.services_by_name['SetPoints']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETPOINTSREQUEST._serialized_start=32
  _SETPOINTSREQUEST._serialized_end=139
  _SETPOINTSRESPONSE._serialized_start=142
  _SETPOINTSRESPONSE._serialized_end=315
  _SETPOINTS._serialized_start=317
  _SETPOINTS._serialized_end=407
# @@protoc_insertion_point(module_scope)
