# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import set_points_pb2 as set__points__pb2


class SetPointsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSetPoints = channel.unary_unary(
                '/set_points.SetPoints/GetSetPoints',
                request_serializer=set__points__pb2.SetPointsRequest.SerializeToString,
                response_deserializer=set__points__pb2.SetPointsResponse.FromString,
                )


class SetPointsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSetPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SetPointsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSetPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSetPoints,
                    request_deserializer=set__points__pb2.SetPointsRequest.FromString,
                    response_serializer=set__points__pb2.SetPointsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'set_points.SetPoints', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SetPoints(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSetPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/set_points.SetPoints/GetSetPoints',
            set__points__pb2.SetPointsRequest.SerializeToString,
            set__points__pb2.SetPointsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
